config system global
    set hostname "FG-EDGE"
    set admin-telnet enable
    set admin-http enable
    set admin-ssh enable
end
config system ntp
    set server-info "10.0.0.10"
end
config system snmp community
    edit 1
        set name "public"
    next
end
